fix

diff --git a/ccbins_files/ccbins b/ccbins_files/ccbins
--- a/ccbins_files/ccbins
+++ b/ccbins_files/ccbins
@@ -47,6 +47,19 @@ dir=`pwd`; bakloc=/data/local/ccbinsbackup
 locs="/system/bin /system/xbin /system/vendor/bin /system/vendor/xbin /system/product/bin /system/product/xbin"
 [ -f $MODDIR/.loc ] && insloc="$(cat $MODDIR/.loc)" || insloc=/system/bin
 
+# redefined with curl
+test_connection() {
+  (
+  if curl -Is --connect-timeout 3 https://www.google.com | grep -q 'HTTP/.* 200'; then
+    true
+  elif curl -Is --connect-timeout 3 https://www.baidu.com | grep -q 'HTTP/.* 200'; then
+    true
+  else
+    false
+  fi & e_spinner "Testing internet connection"
+  ) && echo " - OK" || { echo " - Error"; false; }
+}
+
 quit() {
   rm -f $MODDIR/tmp
   exit 0
