Revert "change scripting for dynamics"
This reverts commit 6d2be784b0ff18a18748c8a0a4431bf70cb7a0be.

diff --git a/ccbins_files/ccbins b/ccbins_files/ccbins
--- a/ccbins_files/ccbins
+++ b/ccbins_files/ccbins
@@ -185,7 +185,7 @@ remove_binary() {
 
 install_binary() {
   [ "$1" == "-s" ] && local spin=true || spin=false
-  [ "$(echo "$ibinary" | sed 's|.*-||')" == "dynamic" ] && local url="https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/dynamic" || local url="https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary"
+  [ "$file" == "$MODDIR/.binaries" ] && local url="https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary" || local url="https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/raw/$branch/$ibinary/dynamic"
   for i in $(grep -w $binary $file | awk '{print $3}' | sed "s/,/ /g"); do
     check_conflicts
     $spin && { wget -O $MODDIR$insloc/$i $url/$i-$ARCH 2>/dev/null & e_spinner; } || wget -O $MODDIR$insloc/$i $url/$i-$ARCH 2>/dev/null
@@ -296,6 +296,7 @@ remove_binary_menu() {
 }
 
 install_binary_menu() {
+[ "$1" == "-d" ] && local file=$MODDIR/.binaries-dynamic || local file=$MODDIR/.binaries
   clear
   while true; do
     if [ -s $MODDIR/.installed ]; then
@@ -303,9 +304,9 @@ install_binary_menu() {
       curbins="$(echo $curbins | sed 's| |\||g')"
     fi
     if [ -z "$curbins" ] || [ ! -s $MODDIR/.installed ]; then
-      cat $MODDIR/.binaries | awk '{print FNR + 1 ": " $1 " " $2}' > $MODDIR/tmp
+      cat $file | awk '{print FNR + 1 ": " $1 " " $2}' > $MODDIR/tmp
     else
-      grep -Ewv "$curbins" $MODDIR/.binaries | awk '{print FNR + 1 ": " $1 " " $2}' > $MODDIR/tmp
+      grep -Ewv "$curbins" $file | awk '{print FNR + 1 ": " $1 " " $2}' > $MODDIR/tmp
     fi
     [ -s $MODDIR/tmp ] && sed -i "1i0: None, go back to main menu\n1: Install all binaries listed below" $MODDIR/tmp || { print_pause "All binaries are installed!\n"; break; }
     echo "$div"
@@ -332,7 +333,7 @@ install_binary_menu() {
       echo "$(grep -w "$ichoice:" $MODDIR/tmp | awk '{print $2 " " $3}' | sed "s| *$| $insloc|")" >> $MODDIR/.installed
       local binary=$(grep -w "$ichoice:" $MODDIR/tmp | awk '{print $2}')
       local ibinary=$(echo $binary | tr '[:upper:]' '[:lower:]')
-      eval local extras="$(grep -w $binary $MODDIR/.binaries | awk '{print $4}')"
+      eval local extras="$(grep -w $binary $file | awk '{print $4}')" 
       echo "Downloading $binary"
       mkdir -p $MODDIR$insloc
       install_binary -s
@@ -453,8 +454,9 @@ fi
 if test_connection; then
   online=true
   echo -e "\nFetching available binaries"
-  rm -f $MODDIR/.binaries
+  rm -f $MODDIR/.binaries $MODDIR/.binaries-dynamic
   wget -qO $MODDIR/.binaries https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/includes.txt 2>/dev/null & e_spinner
+  wget -qO $MODDIR/.binaries-dynamic https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/$branch/ccbins_files/includes-dynamic.txt 2>/dev/null & e_spinner
   echo " - Done"
   check_updates & e_spinner
   [ -f $MODDIR/.updated ] && { echo -e " - Applying mod updates and restarting"; ccbins && quit; } || echo " - Ccbins is up to date"
@@ -484,17 +486,18 @@ while true; do
   echo "4: List all downloadable binaries"
   echo "5: Remove binary"
   $online && echo "6: Install binary"
-  [ -s $MODDIR/.installed ] && echo "7: Backup current config"
-  [ -d $bakloc ] && echo -e "8: Restore last config\n10: Erase backup config"
+  $online && [ $API -ge 21 ] && echo "7: Install dynamic linked binary"
+  [ -s $MODDIR/.installed ] && echo "8: Backup current config"
+  [ -d $bakloc ] && echo -e "9: Restore last config\n10: Erase backup config"
   echo "Type 'q' at any time to quit"
   while true; do
     read -r choice?'--> '
     echo " "
     case $choice in
       0|1|2|3|4|5|99) break;;
-      6) $online && break || echo "Invalid option! Try again";;
-      7) [ -s $MODDIR/.installed ] && break || echo "Invalid option! Try again";;
-      8|9) [ -d $bakloc ] && break || echo "Invalid option! Try again";;
+      6|7) $online && break || echo "Invalid option! Try again";;
+      8) [ -s $MODDIR/.installed ] && break || echo "Invalid option! Try again";;
+      9|10) [ -d $bakloc ] && break || echo "Invalid option! Try again";;
       q) quit;;
       *) echo "Invalid option! Try again";;
     esac
@@ -508,9 +511,10 @@ while true; do
     4) cat $MODDIR/.binaries | awk '{print $1 " " $2}'; echo " ";;
     5) [ -s $MODDIR/.installed ] && remove_binary_menu || print_pause "No binaries installed!\n";;
     6) install_binary_menu;;
-    7) backup_config;;
-    8) restore_config;;
-    9) rm -rf $bakloc; print_pause "Backup config erased\n";;
+    7) install_binary_menu -d;;
+    8) backup_config;;
+    9) restore_config;;
+    10) rm -rf $bakloc; print_pause "Backup config erased\n";;
     99) hidden_menu;;
   esac
 done
